name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install -g @pocketbasecloud/cli@latest

      - name: Build
        working-directory: web
        env:
          VITE_API_URL: https://my-api.pocketbasecloud.com
        run: |
          npm ci
          npm run build

      - name: Deploy
        working-directory: web
        env:
          PB_TOKEN: ${{ secrets.PB_TOKEN }}
        run: pb cloud frontend deploy --skip-build --no-input
